### ISSUE TITLE
[0.1] `listen` - add an example URL that shows a full path

### ISSUE THREAD

**Issue by tasn** [svix/svix-cli#46]
E.g. `http://localhost:8000/webhook/`

This is to make it clear that the local url should be a full path rather than `http://localhost:8000`. It's obvious in retrospect, but the lack of an example just confused me. :)

**Comment by svix-frank** [comment]
@tasn both the example in the README and in the `--help` text show the example as `http://localhost:8000/webhook/`

Here is the example text for reference:

```
listen creates an on-the-fly publicly accessible URL for use when testing webhooks.

The cli then acts as a proxy forwarding any requests to the given local URL.
This is useful for testing your webhook server locally without having to open a port or
change any nat configuration on your network.

Example:
	svix listen http://localhost:8000/webhook/

The above command will return you a unique URL and forward any POST requests it receives
to http://localhost:8000/webhook/
```

If you think this is sufficient we can close this ticket, otherwise I can try to revise!

**Comment by tasn** [comment]
This is what I'm getting:
```
% svix listen
Error: accepts 1 arg(s), received 0
Usage:
  svix listen localURL [flags]

Flags:
  -h, --help   help for listen

Global Flags:
      --color   colorize output json (default true)

Error: accepts 1 arg(s), received 0
```
I'm not talking about the help text, but the hint. Sorry for the confusion. :)

**Comment by svix-frank** [comment]
fixed in https://github.com/svix/svix-cli/pull/54
