### ISSUE TITLE
Add serverUrl to login command

### ISSUE THREAD

**Issue by IAmArchaic** [svix/svix-cli#76]
**Description**

When generating an App Portal Url an accessToken and a serverUrl are required to be set. Performing the command below without setting the serverUrl results in a 401 response.

`
$ svix authentication dashboard "appId"
`
{
  "code": "authentication_failed",
  "detail": "Invalid token. Have you set the correct server URL?"
}

**Current**

Running `svix login` command queries for token and adds/sets it to the config.toml. It does not ask for a serverUrl. server_url can however be set manually within config.toml

**Proposal**

- Update [docs](https://docs.svix.com/app-portal#giving-your-users-access) to include 
`export SVIX_SERVER_URL='THE_SERVER_URL'`

- Enhance `svix login` to ask for optional serverUrl. Whether provided or not, server_url within the config.toml should also be set.

See Slack [conversation](https://svixcommunity.slack.com/archives/C022BJ2EBHV/p1646926814274139) for reference

**Comment by IAmArchaic** [comment]
@tasn , I remember when I first created a Svix Environment, my serverUrl didn't have a region identifier. Not sure if 'legacy' serverUrls need to be considered here.

**Comment by tasn** [comment]
Yeah, @IAmArchaic, that's my comment above about having a default value that is set to legacy. :)
