### ISSUE TITLE
auto-reconnect to webhook relay

### ISSUE THREAD

**Issue by theRealWardo** [svix/svix-cli#95]
Sometimes I get a connection error from the CLI:

```
Failed to connect to Webhook Relay:
dial tcp: lookup [api.relay.svix.com](http://api.relay.svix.com/) on [::1]:53: read udp [::1]:53254->[::1]:53: read: connection refused
```

Ideally, it gracefully reconnects and I'm right back to receiving webhooks.

Right now, it crashes and I have to manually restart it.

**Comment by tasn** [comment]
There's a PR out btw, just waiting for @svix-andor to respond to the comment and we can release it.
